### ISSUE TITLE
Implement winds

### ISSUE THREAD

**Issue by r59q** [r59q/ShipSimGame#4]
I want winds to be a part of the weather, which will always be present in the world.

## Tasks
- [ ] Decide how to implement
- [ ] Research vector fields
    - Maybe find a library?
- [ ] Make a method in GameManager, that can retrieve the impact Vector at a given point

## Ideas
- Vector fields https://en.wikipedia.org/wiki/Vector_field
