### ISSUE TITLE
Scriptable objects for predefined ship data

### ISSUE THREAD

**Issue by r59q** [r59q/ShipSimGame#5]
Create a scriptable object for a ship's properties such as its speed and acceleration curves.

## Tasks
- [x] Create scriptable object
Should include
- [x] Handling profiles
- [x] Integrate with the ship interface
  - [x] Ship mass
  - [x] Acceleration
  - [x] Turning speed
  - [x] Ship size
    - [x] #16 
    - [x] Test that other ships can see it based on size (just place a ship outside detection range and inside after)
  - [x] Top turning speed
  - [x] Detection range
  - [x] Top speed
- [x] Remove or refactor old implementations
  - [x] OptimalTurnSpeed (loop through keys in AnimCurve and return the highest)
  - [x] CreateMaxSpeed (remove it)

## Thoughts
Some of these properties may be randomly generated when making ships, but it's a nice feature to add at the moment.
