### ISSUE TITLE
Make resource loading better

### ISSUE THREAD

**Issue by r59q** [r59q/ShipSimGame#9]
Currently, the resource loading requires file names to be known in advance. Resources are hard-coded as static variables.

ResourceLoader.cs 
```cs
public static class ResourceLoader
{
     ....
    public static class Boats
    {
        public static Mesh TestBoat => (Resources.Load("Mesh/TestBoat") as GameObject).GetComponent<MeshFilter>().sharedMesh;
    }
     ....

}
```

## Tasks
- [X] Research what system to use
- [x] Figure out how to automize testing of variables set in the inspector
- [x] Rewrite the `ResourceLoaders.cs` script

## Approach
From best practices by Unity https://learn.unity.com/tutorial/assets-resources-and-assetbundles#5c7f8528edbc2a002053b5a7 I noted, that in 3.2. (Proper uses of the Resources system) they write: `Examples of this second case include MonoBehaviour singletons used to host prefabs, or ScriptableObjects`

I think the best approach in this case would be to make ScriptableObjects, that can store references to the assets needed by the code. This can be retrieved from the resources folder to make accessing assets easier, without having to store prefabs, and then get the data from a component, which is the approach currently in use.

## Solved !
ResourceLoader is now in charge of keeping track of the stored assets.

Calling `ResourceLoader.Load` returns a `LoadableAssets` object that will contain references to the objects.

Solution:

```cs
public static class ResourceLoader
{

    private static LoadableAssets storedAssets;

    public static LoadableAssets Load
    {
        get { 
            if (storedAssets == null)
            {
                storedAssets = Resources.Load("LoadableAssets") as LoadableAssets;
                if (storedAssets == null)
                {
                    throw new System.NullReferenceException("WARNING: A LoadableAssets object must be present in a resources folder.");
                }
            }
            return storedAssets;
        }
    }

}
```
## Benefits
The benefits are that we do not need to specify file names in code, but let references handle it through ScriptableObject.
